export const styles = {
  container: "flex flex-col w-full flex-1",
  innerContainer: "w-full px-4 lg:px-6 py-5 flex flex-col gap-5",
  topBar: {
    wrapper: "flex flex-col lg:flex-row lg:items-center justify-between gap-3 bg-white p-4 rounded-xl border border-slate-200/60",
    leftSection: "flex flex-wrap items-center gap-3",
    statusBadge: "flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-600",
    statusIcon: "material-symbols-outlined text-lg",
    statusText: "text-xs font-medium",
    shiftInfo: "flex items-center gap-2",
    shiftNumber: "text-xs text-slate-400 font-mono-num",
    shiftDot: "text-slate-200",
    operatorText: "text-sm text-slate-500",
    operatorName: "text-slate-700 font-medium",
    rightSection: "flex flex-wrap items-center gap-3",
    timeWrapper: "flex items-center gap-2",
    timeIcon: "material-symbols-outlined text-slate-300 text-lg",
    timeLabel: "text-[10px] text-slate-400 uppercase tracking-wider",
    timeValue: "text-xs text-slate-600 font-mono-num font-medium",
    fundWrapper: "flex items-center gap-2 bg-slate-50 px-3 py-1.5 rounded-lg",
    fundIcon: "material-symbols-outlined text-slate-400 text-lg",
    fundLabel: "text-[10px] text-slate-400 uppercase tracking-wider",
    fundValue: "text-sm text-slate-700 font-bold font-mono-num",
    closeButton: "flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-red-50 hover:bg-red-100 text-red-600 border border-transparent hover:border-red-200 transition-all font-medium",
    closeIcon: "material-symbols-outlined text-base",
    closeText: "text-xs font-medium",
  },
  metrics: {
    grid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4",
    card: "bg-white p-4 rounded-xl border border-slate-200/60 flex flex-col justify-between hover:border-slate-300/60 transition-all",
    header: "flex items-center justify-between mb-3",
    title: "text-xs text-slate-400 uppercase tracking-wider font-medium",
    iconWrapperSales: "w-8 h-8 rounded-lg bg-blue-50 text-blue-500 flex items-center justify-center",
    iconWrapperCash: "w-8 h-8 rounded-lg bg-emerald-50 text-emerald-500 flex items-center justify-center",
    iconWrapperPix: "w-8 h-8 rounded-lg bg-amber-50 text-amber-500 flex items-center justify-center",
    iconWrapperCard: "w-8 h-8 rounded-lg bg-indigo-50 text-indigo-500 flex items-center justify-center",
    icon: "material-symbols-outlined text-lg",
    value: "text-2xl font-bold font-mono-num text-slate-800 tracking-tight",
    subtextSales: "flex items-center gap-1 mt-1 text-slate-400 text-xs",
    subtextCash: "flex items-center gap-1 mt-1 text-slate-400 text-xs",
    subtextPix: "flex items-center gap-1 mt-1 text-slate-400 text-xs",
    subtextCard: "flex items-center justify-between mt-1 text-slate-400 text-xs",
    subtextIcon: "material-symbols-outlined text-sm",
    barWrapper: "w-full bg-slate-100 h-1 rounded-full mt-3 overflow-hidden",
    barSales: "bg-blue-400 h-full w-[78%] rounded-full",
    barCash: "bg-emerald-400 h-full w-[65%] rounded-full",
    barPix: "bg-amber-400 h-full w-[45%] rounded-full",
    barCard: "bg-indigo-400 h-full w-[85%] rounded-full",
  },
  layout: {
    grid: "grid grid-cols-1 lg:grid-cols-12 gap-5 items-start",
    leftCol: "lg:col-span-4 flex flex-col gap-4",
    rightCol: "lg:col-span-8 flex flex-col gap-4 bg-white p-5 rounded-xl border border-slate-200/60 min-h-[500px]",
  },
  actions: {
    card: "bg-white p-4 rounded-xl border border-slate-200/60 flex flex-col gap-3",
    header: "flex items-center justify-between",
    title: "text-sm font-semibold text-slate-700",
    shortcut: "px-2 py-0.5 rounded-md bg-slate-100 text-slate-500 text-xs font-mono-num",
    desc: "text-xs text-slate-400",
    grid: "grid grid-cols-2 gap-2.5",
    btnSangria: "flex flex-col items-center justify-center gap-1.5 p-4 rounded-xl bg-red-50 hover:bg-red-100 border border-transparent hover:border-red-200 text-red-600 transition-all group min-h-[96px]",
    btnSuprimento: "flex flex-col items-center justify-center gap-1.5 p-4 rounded-xl bg-slate-50 hover:bg-slate-100 border border-transparent hover:border-slate-200 text-slate-600 transition-all group min-h-[96px]",
    btnIconSangria: "material-symbols-outlined text-red-500 group-hover:scale-110 transition-transform text-2xl",
    btnIconSuprimento: "material-symbols-outlined text-slate-400 group-hover:scale-110 transition-transform text-2xl",
    btnTitle: "text-sm font-semibold text-slate-700",
    btnSubSangria: "text-[11px] text-red-400",
    btnSubSuprimento: "text-[11px] text-slate-400",
  },
  summary: {
    card: "bg-white p-4 rounded-xl border border-slate-200/60 flex flex-col gap-2",
    header: "flex items-center justify-between pb-2 border-b border-slate-100",
    title: "text-sm font-semibold text-slate-700",
    icon: "material-symbols-outlined text-slate-300 text-base",
    row: "flex items-center justify-between py-1.5 text-xs",
    label: "text-slate-400",
    valNeutral: "font-mono-num text-slate-600 font-medium",
    valPositive: "font-mono-num text-emerald-600 font-medium",
    valNegative: "font-mono-num text-red-500 font-medium",
    totalWrapper: "mt-2 p-3 rounded-lg bg-slate-50 flex items-center justify-between",
    totalLabel: "text-[11px] text-slate-400 uppercase font-medium",
    totalValue: "text-sm text-slate-800 font-bold font-mono-num",
  },
  peripherals: {
    card: "bg-white p-4 rounded-xl border border-slate-200/60 flex flex-col gap-2",
    title: "text-xs text-slate-400 uppercase tracking-wider font-medium",
    grid: "grid grid-cols-2 gap-2 mt-1",
    item: "p-2.5 rounded-lg bg-slate-50 flex items-center gap-2",
    dotActive: "w-1.5 h-1.5 rounded-full bg-emerald-400",
    dotInactive: "w-1.5 h-1.5 rounded-full bg-slate-300",
    textActive: "text-xs text-slate-600",
    textInactive: "text-xs text-slate-400",
  },
  ledger: {
    header: "flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-100",
    titleWrapper: "flex items-center gap-2",
    title: "text-sm font-semibold text-slate-700",
    badge: "px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-500 text-[10px] font-medium",
    desc: "text-xs text-slate-400 mt-0.5",
    filterWrapper: "flex items-center gap-1 bg-slate-100/80 p-1 rounded-lg",
    filterBtnBase: "px-3 py-1 rounded-md text-xs font-medium transition-colors",
    filterBtnActive: "bg-white text-slate-700 shadow-sm",
    filterBtnInactive: "text-slate-400 hover:text-slate-600",
    tableWrapper: "overflow-x-auto w-full flex-1",
    table: "w-full text-left text-xs",
    thead: "bg-slate-50/80 text-slate-400 uppercase tracking-wider text-[11px] border-b border-slate-100 font-medium",
    thLeft: "py-3 px-3 rounded-l",
    th: "py-3 px-3",
    thRight: "py-3 px-3 text-right rounded-r",
    tbody: "divide-y divide-slate-50",
    tr: "hover:bg-slate-50/50 transition-colors",
    tdTime: "py-3 px-3 font-mono-num text-slate-400 whitespace-nowrap",
    tdType: "py-3 px-3",
    typeWrapper: "flex items-center gap-1.5",
    docRef: "font-mono-num text-[11px] text-slate-300",
    tdReason: "py-3 px-3 text-slate-500",
    tdOperator: "py-3 px-3",
    operatorName: "font-medium text-slate-600",
    operatorAuth: "font-mono-num text-[11px] text-slate-300",
    tdAmountBase: "py-3 px-3 text-right font-mono-num font-semibold whitespace-nowrap text-sm",
    emptyTr: "py-12 text-center text-slate-300",
    footer: "mt-auto pt-3 border-t border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between text-slate-400 text-xs",
    printBtn: "flex items-center gap-1.5 text-slate-500 hover:text-slate-700 font-medium transition-colors mt-2 sm:mt-0",
    printIcon: "material-symbols-outlined text-base",
  },
  modal: {
    overlay: "fixed inset-0 z-50 bg-black/30 backdrop-blur-sm flex items-center justify-center p-4",
    box: "bg-white w-full max-w-lg rounded-2xl shadow-xl border border-slate-200/60 p-6 flex flex-col gap-4",
    header: "flex items-center justify-between pb-3 border-b border-slate-100",
    headerLeft: "flex items-center gap-3",
    iconWrapperSangria: "w-10 h-10 rounded-xl flex items-center justify-center bg-red-50 text-red-500",
    iconWrapperSuprimento: "w-10 h-10 rounded-xl flex items-center justify-center bg-slate-100 text-slate-500",
    iconWrapperClose: "w-10 h-10 rounded-xl flex items-center justify-center bg-red-50 text-red-500",
    icon: "material-symbols-outlined text-xl",
    title: "text-base font-semibold text-slate-800",
    desc: "text-xs text-slate-400",
    closeBtn: "w-8 h-8 rounded-lg hover:bg-slate-100 flex items-center justify-center text-slate-300 hover:text-slate-500 transition-colors",
    closeBtnIcon: "material-symbols-outlined text-lg",
    form: "flex flex-col gap-3.5",
    fieldGroup: "flex flex-col gap-1.5",
    label: "text-xs text-slate-400 uppercase font-medium",
    inputWrapper: "relative flex items-center",
    currencySymbol: "absolute left-3.5 text-lg font-semibold text-slate-300",
    inputLarge: "w-full h-12 pl-12 pr-4 bg-slate-50 border border-slate-200/60 text-slate-800 text-2xl font-mono-num font-bold rounded-xl outline-none focus:bg-white focus:border-blue-400 focus:ring-2 focus:ring-blue-100 transition-all",
    select: "h-10 px-3 bg-slate-50 border border-slate-200/60 text-slate-600 rounded-xl text-sm outline-none focus:bg-white focus:border-blue-400 transition-all",
    inputNormal: "h-10 px-3 bg-slate-50 border border-slate-200/60 text-slate-600 rounded-xl text-sm outline-none focus:bg-white focus:border-blue-400 transition-all",
    inputBlind: "h-11 px-3 bg-slate-50 border border-slate-200/60 text-slate-600 rounded-xl font-mono-num text-sm outline-none focus:bg-white focus:border-blue-400 transition-all",
    footer: "flex items-center justify-end gap-2 pt-3 border-t border-slate-100",
    btnCancel: "px-4 h-10 rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-200 font-medium text-sm transition-colors",
    btnConfirmSangria: "px-5 h-10 rounded-xl text-white font-semibold text-sm transition-colors flex items-center gap-1.5 bg-red-500 hover:bg-red-600",
    btnConfirmSuprimento: "px-5 h-10 rounded-xl text-white font-semibold text-sm transition-colors flex items-center gap-1.5 bg-slate-900 hover:bg-slate-800",
    btnConfirmClose: "px-5 h-10 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-semibold text-sm transition-colors",
    btnConfirmIcon: "material-symbols-outlined text-base",
    summaryBox: "p-4 bg-slate-50 rounded-xl flex flex-col gap-2 text-xs text-slate-500",
    summaryRow: "flex justify-between",
    summaryValSuccess: "text-slate-700 font-semibold font-mono-num text-sm",
    summaryValNeutral: "text-slate-700 font-medium font-mono-num text-sm",
    summaryNote: "text-[11px] text-slate-400 mt-1",
  }
};
