export const styles = {
  container: "flex flex-col w-full flex-1",
  innerContainer: "w-full px-4 lg:px-6 py-4 flex flex-col gap-4",
  topBar: {
    wrapper: "flex flex-col lg:flex-row lg:items-center justify-between gap-3 bg-white p-4 rounded-xl border border-slate-200 shadow-xs",
    leftSection: "flex flex-wrap items-center gap-4",
    statusBadge: "flex items-center gap-1.5 bg-emerald-50 border border-emerald-200 px-3 py-1.5 rounded-lg",
    statusIcon: "material-symbols-outlined text-emerald-600 text-xl",
    statusText: "font-mono-num text-xs text-emerald-800 font-bold",
    shiftInfo: "flex items-center gap-2",
    shiftNumber: "font-mono-num text-xs text-slate-500 font-semibold",
    shiftDot: "text-slate-300",
    operatorText: "text-sm text-slate-700",
    operatorName: "text-slate-900 font-semibold",
    rightSection: "flex flex-wrap items-center gap-4",
    timeWrapper: "flex items-center gap-2",
    timeIcon: "material-symbols-outlined text-slate-400 text-lg",
    timeLabel: "font-mono-num text-[10px] text-slate-500 uppercase tracking-wider",
    timeValue: "font-mono-num text-xs text-slate-800 font-semibold",
    fundWrapper: "flex items-center gap-2.5 bg-blue-50/80 border border-blue-100 px-3 py-1.5 rounded-lg",
    fundIcon: "material-symbols-outlined text-blue-600 text-lg",
    fundLabel: "font-mono-num text-[10px] text-blue-700 uppercase tracking-wider font-semibold",
    fundValue: "font-mono-num text-sm text-blue-900 font-bold",
    closeButton: "flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 transition-colors font-medium shadow-xs",
    closeIcon: "material-symbols-outlined text-base",
    closeText: "font-mono-num text-xs uppercase tracking-wider font-bold",
  },
  metrics: {
    grid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4",
    card: "bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-between hover:border-slate-300 transition-all",
    header: "flex items-center justify-between mb-2",
    title: "font-mono-num text-slate-500 uppercase tracking-wider text-[11px] font-bold",
    iconWrapperSales: "w-8 h-8 rounded-lg bg-blue-100 text-blue-700 flex items-center justify-center",
    iconWrapperCash: "w-8 h-8 rounded-lg bg-emerald-100 text-emerald-700 flex items-center justify-center",
    iconWrapperPix: "w-8 h-8 rounded-lg bg-amber-100 text-amber-700 flex items-center justify-center",
    iconWrapperCard: "w-8 h-8 rounded-lg bg-indigo-100 text-indigo-700 flex items-center justify-center",
    icon: "material-symbols-outlined text-lg",
    value: "text-2xl font-bold font-mono-num text-slate-900 tracking-tight",
    subtextSales: "flex items-center gap-1 mt-1 text-emerald-700 font-mono-num text-xs font-semibold",
    subtextCash: "flex items-center gap-1 mt-1 text-slate-600 font-mono-num text-xs",
    subtextPix: "flex items-center gap-1 mt-1 text-amber-700 font-mono-num text-xs font-semibold",
    subtextCard: "flex items-center justify-between mt-1 text-slate-600 font-mono-num text-xs",
    subtextIcon: "material-symbols-outlined text-sm",
    barWrapper: "w-full bg-slate-100 h-1.5 rounded-full mt-3 overflow-hidden",
    barSales: "bg-blue-600 h-full w-[78%] rounded-full",
    barCash: "bg-emerald-600 h-full w-[65%] rounded-full",
    barPix: "bg-amber-500 h-full w-[45%] rounded-full",
    barCard: "bg-indigo-600 h-full w-[85%] rounded-full",
  },
  layout: {
    grid: "grid grid-cols-1 lg:grid-cols-12 gap-4 items-start",
    leftCol: "lg:col-span-4 flex flex-col gap-4",
    rightCol: "lg:col-span-8 flex flex-col gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-xs min-h-[500px]",
  },
  actions: {
    card: "bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-col gap-3",
    header: "flex items-center justify-between",
    title: "text-base font-bold text-slate-900",
    shortcut: "px-2 py-0.5 rounded bg-blue-50 text-blue-700 border border-blue-200 font-mono-num text-xs font-bold",
    desc: "text-xs text-slate-600",
    grid: "grid grid-cols-2 gap-2.5",
    btnSangria: "flex flex-col items-center justify-center gap-1 p-3.5 rounded-xl bg-rose-50 hover:bg-rose-100 border border-rose-200 text-rose-800 transition-all group shadow-xs min-h-[96px]",
    btnSuprimento: "flex flex-col items-center justify-center gap-1 p-3.5 rounded-xl bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 text-emerald-800 transition-all group shadow-xs min-h-[96px]",
    btnIconSangria: "material-symbols-outlined text-rose-600 group-hover:scale-110 transition-transform text-3xl",
    btnIconSuprimento: "material-symbols-outlined text-emerald-600 group-hover:scale-110 transition-transform text-3xl",
    btnTitle: "text-sm font-bold text-slate-900",
    btnSubSangria: "font-mono-num text-[11px] text-rose-700 font-medium",
    btnSubSuprimento: "font-mono-num text-[11px] text-emerald-700 font-medium",
  },
  summary: {
    card: "bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-col gap-2",
    header: "flex items-center justify-between pb-1 border-b border-slate-100",
    title: "text-sm font-bold text-slate-900",
    icon: "material-symbols-outlined text-emerald-600 text-base",
    row: "flex items-center justify-between py-1 text-xs",
    label: "text-slate-600 font-medium",
    valNeutral: "font-mono-num text-slate-800 font-semibold",
    valPositive: "font-mono-num text-emerald-700 font-bold",
    valNegative: "font-mono-num text-rose-600 font-bold",
    totalWrapper: "mt-1.5 p-2.5 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-between",
    totalLabel: "font-mono-num text-[11px] text-slate-700 uppercase font-bold",
    totalValue: "font-mono-num text-sm text-emerald-700 font-bold",
  },
  peripherals: {
    card: "bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-col gap-2",
    title: "font-mono-num text-slate-500 uppercase tracking-wider text-[11px] font-bold",
    grid: "grid grid-cols-2 gap-2 mt-1",
    item: "p-2 rounded bg-slate-50 border border-slate-200 flex items-center gap-2",
    dotActive: "w-2 h-2 rounded-full bg-emerald-500",
    dotInactive: "w-2 h-2 rounded-full bg-slate-400",
    textActive: "font-mono-num text-slate-700 text-xs font-medium",
    textInactive: "font-mono-num text-slate-500 text-xs font-medium",
  },
  ledger: {
    header: "flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100",
    titleWrapper: "flex items-center gap-2",
    title: "text-base font-bold text-slate-900",
    badge: "px-2 py-0.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700 font-mono-num text-[10px] font-bold",
    desc: "text-xs text-slate-500 mt-0.5",
    filterWrapper: "flex items-center gap-1.5 bg-slate-100 p-1 rounded-lg",
    filterBtnBase: "px-3 py-1 rounded-md font-mono-num text-xs font-bold transition-colors",
    filterBtnActive: "bg-white text-blue-700 shadow-xs",
    filterBtnInactive: "text-slate-600 hover:text-slate-900",
    tableWrapper: "overflow-x-auto w-full flex-1",
    table: "w-full text-left text-xs",
    thead: "bg-slate-50 text-slate-600 font-mono-num uppercase tracking-wider text-[11px] border-b border-slate-200",
    thLeft: "py-2.5 px-3 rounded-l",
    th: "py-2.5 px-3",
    thRight: "py-2.5 px-3 text-right rounded-r",
    tbody: "divide-y divide-slate-100",
    tr: "hover:bg-slate-50 transition-colors",
    tdTime: "py-3 px-3 font-mono-num text-slate-600 whitespace-nowrap",
    tdType: "py-3 px-3",
    typeWrapper: "flex items-center gap-1.5",
    docRef: "font-mono-num text-[11px] text-slate-500",
    tdReason: "py-3 px-3 text-slate-700",
    tdOperator: "py-3 px-3",
    operatorName: "font-medium text-slate-900",
    operatorAuth: "font-mono-num text-[11px] text-slate-500",
    tdAmountBase: "py-3 px-3 text-right font-mono-num font-bold whitespace-nowrap text-sm",
    emptyTr: "py-10 text-center text-slate-400",
    footer: "mt-auto pt-3 border-t border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between text-slate-500 font-mono-num text-xs",
    printBtn: "flex items-center gap-1.5 text-blue-600 hover:text-blue-800 font-semibold transition-colors mt-2 sm:mt-0",
    printIcon: "material-symbols-outlined text-base",
  },
  modal: {
    overlay: "fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-xs flex items-center justify-center p-4",
    box: "bg-white w-full max-w-lg rounded-xl shadow-2xl border border-slate-200 p-5 flex flex-col gap-4",
    header: "flex items-center justify-between pb-2 border-b border-slate-100",
    headerLeft: "flex items-center gap-3",
    iconWrapperSangria: "w-10 h-10 rounded-lg flex items-center justify-center bg-rose-100 text-rose-700",
    iconWrapperSuprimento: "w-10 h-10 rounded-lg flex items-center justify-center bg-emerald-100 text-emerald-700",
    iconWrapperClose: "w-10 h-10 rounded-lg flex items-center justify-center bg-rose-100 text-rose-700",
    icon: "material-symbols-outlined text-xl",
    title: "text-base font-bold text-slate-900",
    desc: "text-xs text-slate-500 font-mono-num",
    closeBtn: "w-8 h-8 rounded-lg hover:bg-slate-100 flex items-center justify-center text-slate-400 hover:text-slate-700",
    closeBtnIcon: "material-symbols-outlined text-lg",
    form: "flex flex-col gap-3.5",
    fieldGroup: "flex flex-col gap-1",
    label: "text-xs font-mono-num font-semibold text-slate-600 uppercase",
    inputWrapper: "relative flex items-center",
    currencySymbol: "absolute left-3.5 text-lg font-bold text-slate-400",
    inputLarge: "w-full h-12 pl-12 pr-4 bg-slate-50 border border-slate-300 text-slate-900 text-2xl font-mono-num font-bold rounded-lg outline-none focus:bg-white focus:border-blue-600",
    select: "h-10 px-3 bg-slate-50 border border-slate-300 text-slate-800 rounded-lg text-sm outline-none focus:bg-white focus:border-blue-600",
    inputNormal: "h-10 px-3 bg-slate-50 border border-slate-300 text-slate-800 rounded-lg text-sm outline-none focus:bg-white focus:border-blue-600",
    inputBlind: "h-11 px-3 bg-slate-50 border border-slate-300 text-slate-800 rounded-lg font-mono-num text-sm outline-none focus:bg-white focus:border-blue-600",
    footer: "flex items-center justify-end gap-2 pt-2 border-t border-slate-100",
    btnCancel: "px-4 h-10 rounded-lg bg-slate-100 text-slate-700 hover:bg-slate-200 font-semibold text-xs",
    btnConfirmSangria: "px-5 h-10 rounded-lg text-white font-bold text-xs shadow-xs transition-colors flex items-center gap-1.5 bg-rose-600 hover:bg-rose-700",
    btnConfirmSuprimento: "px-5 h-10 rounded-lg text-white font-bold text-xs shadow-xs transition-colors flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-700",
    btnConfirmClose: "px-5 h-10 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-xs",
    btnConfirmIcon: "material-symbols-outlined text-base",
    summaryBox: "p-3 bg-slate-50 border border-slate-200 rounded-lg flex flex-col gap-1.5 text-xs text-slate-600",
    summaryRow: "flex justify-between",
    summaryValSuccess: "text-emerald-700 font-bold font-mono-num text-sm",
    summaryValNeutral: "text-slate-900 font-semibold font-mono-num text-sm",
    summaryNote: "text-[11px] text-slate-500 mt-1",
  }
};
