export const styles = {
  container: 'flex flex-col w-full flex-1',
  contentWrapper: 'w-full px-4 lg:px-6 py-5 flex flex-col gap-5',

  /* Top Search Strip */
  topStrip: 'grid grid-cols-1 xl:grid-cols-12 gap-4 items-stretch',
  searchBox: 'xl:col-span-8 bg-white border border-slate-200/60 p-4 rounded-xl flex flex-col justify-center',
  searchHeader: 'flex flex-wrap items-center justify-between mb-2 px-1 gap-2',
  searchHeaderLeft: 'flex items-center gap-2',
  searchTitle: 'text-xs text-slate-400 uppercase tracking-wider font-medium',
  searchStatusDot: 'w-1.5 h-1.5 rounded-full bg-emerald-400',
  searchStatusText: 'text-xs text-slate-400',
  searchShortcuts: 'flex flex-wrap items-center gap-2 text-slate-300 text-xs',
  searchInputWrapper: 'relative flex items-center',
  searchIconWrapper: 'absolute left-3.5 flex items-center pointer-events-none text-slate-300',
  searchIcon: 'material-symbols-outlined text-xl',
  searchInput: 'w-full bg-slate-50 border border-slate-200/60 text-slate-800 text-sm pl-11 pr-24 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-400 focus:bg-white placeholder:text-slate-300 transition-all',
  searchBadgesWrapper: 'absolute right-3 flex items-center gap-1.5',
  searchBadgeF2: 'px-2 py-0.5 rounded-md bg-slate-100 text-slate-400 text-xs hidden sm:block',
  searchBadgeFocus: 'px-2 py-0.5 rounded-md bg-slate-100 text-slate-400 text-[11px] hidden sm:block',

  /* Metrics Cards */
  metricsStrip: 'xl:col-span-4 grid grid-cols-1 sm:grid-cols-3 gap-3',
  metricCard: 'bg-white border border-slate-200/60 p-3 rounded-xl flex flex-col justify-between',
  metricTitle: 'text-[11px] text-slate-400 uppercase font-medium',
  metricValueWrapper: 'flex items-baseline gap-1 my-1',
  metricValue: 'text-xl font-bold text-slate-800 font-mono-num',
  metricUnit: 'text-xs text-slate-400',
  metricStatusWrapper: 'text-[11px] font-medium flex items-center gap-1',
  metricStatusIcon: 'material-symbols-outlined text-xs',

  /* Category Filter */
  categoryFilterBar: 'flex items-center gap-2 overflow-x-auto pb-1',
  categoryButtonBase: 'px-3.5 py-2 rounded-xl text-xs font-medium flex items-center gap-2 transition-all shrink-0',
  categoryButtonActive: 'bg-slate-900 text-white',
  categoryButtonInactive: 'bg-white border border-slate-200/60 hover:bg-slate-50 text-slate-500',
  categoryIcon: 'material-symbols-outlined text-base',
  categoryShortcutBase: 'px-1.5 py-0.5 rounded-md text-[10px] hidden sm:block',
  categoryShortcutActive: 'bg-white/15 text-white/80',
  categoryShortcutInactive: 'bg-slate-100 text-slate-400',

  /* Products List Layout */
  mainLayout: 'grid grid-cols-1 lg:grid-cols-12 gap-5 items-start',
  productsGrid: 'lg:col-span-12 flex flex-col gap-3',
  productCard: 'group relative bg-white border border-slate-200/60 hover:border-slate-300 p-3 rounded-xl transition-all flex items-center justify-between cursor-pointer gap-4',
  productImageWrapper: 'relative w-16 h-16 rounded-lg bg-slate-50 overflow-hidden shrink-0',
  productImage: 'w-full h-full object-cover group-hover:scale-105 transition-transform duration-300',
  productCodeBadge: 'hidden',
  productCategoryBadgeBase: 'hidden',
  productCategoryBadgeAmber: 'bg-amber-50 text-amber-600',
  productCategoryBadgeBlue: 'bg-blue-50 text-blue-500',
  productInfoWrapper: 'flex-1 min-w-0',
  productTitle: 'text-sm font-semibold text-slate-700 group-hover:text-slate-900 line-clamp-1 transition-colors',
  productBrand: 'text-xs text-slate-400',
  productActionWrapper: 'flex items-center gap-6 shrink-0',
  productPriceRow: 'flex flex-row items-center gap-6',
  productPriceCol: 'flex flex-col',
  productPriceLabel: 'text-[10px] text-slate-400 uppercase',
  productPriceValueWrapper: 'flex items-baseline gap-0.5',
  productPriceCurrency: 'text-xs text-slate-500 font-mono-num',
  productPriceValue: 'text-xl font-bold text-slate-800 font-mono-num',
  productStockCol: 'text-left sm:text-right flex flex-col items-start sm:items-end',
  productStockLabel: 'text-[10px] text-slate-400 uppercase',
  productStockValueBase: 'text-sm font-semibold font-mono-num',
  editButton: 'h-9 w-9 rounded-lg bg-slate-50 hover:bg-blue-50 text-slate-500 hover:text-blue-600 border border-slate-200/60 hover:border-blue-200 text-xs font-medium flex items-center justify-center transition-all shrink-0',
  deleteButton: 'h-9 w-9 rounded-lg bg-slate-50 hover:bg-red-50 text-slate-500 hover:text-red-600 border border-slate-200/60 hover:border-red-200 text-xs font-medium flex items-center justify-center transition-all shrink-0',
  emptyState: 'col-span-full py-16 text-center text-slate-300 bg-white border border-slate-200/60 rounded-xl',
  emptyStateIcon: 'material-symbols-outlined text-4xl block mb-3 text-slate-200',

  /* Sidebar */
  sidebarLayout: 'lg:col-span-3 flex flex-col gap-4 sticky top-20',
  scaleWidgetUnit: 'text-sm text-slate-500',

  /* Modal Import */
  modalOverlay: 'fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/30 backdrop-blur-sm',
  modalBox: 'bg-white rounded-2xl shadow-xl border border-slate-200/60 p-6 w-full max-w-md',
  modalHeader: 'flex items-center justify-between mb-4',
  modalTitle: 'text-lg font-bold text-slate-800',
  modalCloseBtn: 'text-slate-400 hover:text-slate-600 transition-colors',
  modalBody: 'flex flex-col gap-5',
  modalInputWrapper: 'flex flex-col gap-2',
  modalLabel: 'text-xs font-semibold text-slate-700',
  modalFileInput: 'block w-full text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 transition-all border border-slate-200/60 rounded-xl bg-slate-50 p-2 cursor-pointer',
  modalFooter: 'flex items-center gap-3 pt-4 border-t border-slate-100',
  btnCancel: 'flex-1 px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-600 text-sm font-semibold rounded-xl transition-colors',
  btnConfirm: 'flex-1 px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white text-sm font-semibold rounded-xl transition-colors',
  linkDownload: 'text-xs text-blue-600 hover:text-blue-800 underline mt-1 text-center font-medium cursor-pointer'
};
