export const styles = {
  container: 'flex flex-col w-full flex-1',
  contentWrapper: 'w-full px-4 lg:px-6 py-4 flex flex-col gap-4',
  topStrip: 'grid grid-cols-1 xl:grid-cols-12 gap-3 items-stretch',
  searchBox: 'xl:col-span-8 bg-white border border-slate-200 p-3 rounded-lg shadow-xs flex flex-col justify-center',
  searchHeader: 'flex items-center justify-between mb-1 px-1',
  searchHeaderLeft: 'flex items-center gap-2',
  searchTitle: 'font-mono-num text-xs text-blue-700 uppercase tracking-wider font-bold',
  searchStatusDot: 'w-1.5 h-1.5 rounded-full bg-emerald-500',
  searchStatusText: 'font-mono-num text-xs text-slate-500 font-medium',
  searchShortcuts: 'flex items-center gap-2 text-slate-500 font-mono-num text-xs',
  searchInputWrapper: 'relative flex items-center',
  searchIconWrapper: 'absolute left-3.5 flex items-center pointer-events-none text-blue-700',
  searchIcon: 'material-symbols-outlined text-2xl font-bold',
  searchInput: 'w-full bg-[#f8fafc] border border-slate-300 text-slate-900 text-base pl-12 pr-28 py-2.5 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600 focus:bg-white placeholder:text-slate-400 transition-all font-medium',
  searchBadgesWrapper: 'absolute right-2.5 flex items-center gap-1.5',
  searchBadgeF2: 'px-2 py-0.5 rounded bg-blue-100 text-blue-700 font-mono-num text-xs font-bold',
  searchBadgeFocus: 'px-2 py-0.5 rounded bg-slate-200 text-slate-700 font-mono-num text-[11px] font-semibold',
  metricsStrip: 'xl:col-span-4 grid grid-cols-3 gap-2',
  metricCard: 'bg-white border border-slate-200 p-2.5 rounded-lg flex flex-col justify-between shadow-xs',
  metricTitle: 'font-mono-num text-[11px] text-slate-500 uppercase font-semibold',
  metricValueWrapper: 'flex items-baseline gap-1 my-0.5',
  metricValue: 'text-xl font-bold text-slate-900 font-mono-num',
  metricUnit: 'text-xs text-slate-500 font-mono-num',
  metricStatusWrapper: 'text-[11px] font-mono-num font-semibold flex items-center gap-1',
  metricStatusIcon: 'material-symbols-outlined text-xs font-bold',
  categoryFilterBar: 'flex items-center gap-2 overflow-x-auto pb-1',
  categoryButtonBase: 'px-3.5 py-2 rounded-lg font-mono-num text-xs font-bold flex items-center gap-2 transition-colors shrink-0 shadow-xs',
  categoryButtonActive: 'bg-[#004ac6] text-white shadow-sm',
  categoryButtonInactive: 'bg-white border border-slate-200 hover:bg-slate-50 hover:border-slate-300 text-slate-700',
  categoryIcon: 'material-symbols-outlined text-base',
  categoryShortcutBase: 'px-1.5 py-0.5 rounded text-[10px] font-mono-num',
  categoryShortcutActive: 'bg-white/20 text-white',
  categoryShortcutInactive: 'bg-slate-100 text-slate-600',
  mainLayout: 'grid grid-cols-1 lg:grid-cols-12 gap-4 items-start',
  productsGrid: 'lg:col-span-9 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3.5',
  productCard: 'group relative bg-white border border-slate-200 hover:border-blue-400 hover:shadow-md p-3 rounded-lg shadow-xs transition-all flex flex-col justify-between cursor-pointer',
  productImageWrapper: 'relative w-full h-32 rounded bg-slate-100 border border-slate-200/80 overflow-hidden mb-2',
  productImage: 'w-full h-full object-cover group-hover:scale-105 transition-transform duration-300',
  productCodeBadge: 'absolute top-2 left-2 px-2 py-0.5 rounded bg-white/95 text-[#004ac6] border border-slate-200 font-mono-num text-[11px] font-bold shadow-xs',
  productCategoryBadgeBase: 'absolute bottom-2 right-2 px-2 py-0.5 rounded font-mono-num text-[11px] font-bold shadow-xs',
  productCategoryBadgeAmber: 'bg-amber-50 text-amber-800 border border-amber-200',
  productCategoryBadgeBlue: 'bg-blue-50 text-blue-700 border border-blue-200',
  productInfoWrapper: 'mb-2',
  productTitle: 'text-sm font-bold text-slate-900 group-hover:text-blue-700 line-clamp-1 transition-colors',
  productBrand: 'text-xs text-slate-500 font-medium',
  productActionWrapper: 'pt-1 border-t border-slate-100',
  productPriceRow: 'flex items-baseline justify-between mb-2.5',
  productPriceCol: 'flex flex-col',
  productPriceLabel: 'text-[10px] font-mono-num text-slate-500 font-bold uppercase',
  productPriceValueWrapper: 'flex items-baseline gap-0.5',
  productPriceCurrency: 'text-xs font-mono-num text-emerald-700 font-bold',
  productPriceValue: 'text-xl font-extrabold text-slate-900 font-mono-num',
  productStockCol: 'text-right flex flex-col items-end',
  productStockLabel: 'text-[10px] font-mono-num text-slate-500 font-bold uppercase',
  productStockValueBase: 'text-sm font-bold font-mono-num',
  productActionButton: 'w-full h-10 rounded-lg bg-slate-100 hover:bg-[#004ac6] text-slate-800 hover:text-white border border-slate-200 hover:border-[#004ac6] font-mono-num text-xs font-bold flex items-center justify-center gap-1.5 transition-colors group-hover:bg-[#004ac6] group-hover:text-white',
  productActionIcon: 'material-symbols-outlined text-base',
  productActionShortcut: 'px-1.5 py-0.5 rounded bg-white text-blue-700 text-[10px] font-bold border border-slate-200',
  emptyState: 'col-span-full py-16 text-center text-slate-400 bg-white border border-slate-200 rounded-lg',
  emptyStateIcon: 'material-symbols-outlined text-4xl block mb-2 text-slate-300',
  sidebarLayout: 'lg:col-span-3 flex flex-col gap-3 sticky top-32',
  activeSaleCard: 'bg-white border border-slate-200 p-4 rounded-lg shadow-xs flex flex-col gap-3',
  activeSaleHeader: 'flex items-center justify-between',
  activeSaleTitleWrapper: 'flex items-center gap-1.5',
  activeSaleIcon: 'material-symbols-outlined text-blue-700 text-lg font-bold',
  activeSaleTitle: 'text-xs font-bold font-mono-num text-slate-900 tracking-wider',
  activeSaleStatus: 'px-2 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 text-[10px] font-mono-num font-bold',
  totalDisplay: 'bg-[#f8fafc] border border-slate-200 p-3.5 rounded-lg flex flex-col justify-center',
  totalDisplayLabel: 'text-[10px] font-mono-num text-slate-500 uppercase tracking-wider font-semibold',
  totalDisplayValueWrapper: 'flex items-baseline gap-1 my-0.5',
  totalDisplayCurrency: 'text-xl font-bold text-emerald-700 font-mono-num',
  totalDisplayValue: 'text-4xl font-extrabold text-slate-900 font-mono-num tracking-tight',
  totalDisplayFooter: 'flex items-center justify-between text-xs text-slate-600 font-mono-num font-medium',
  recentItemsHeader: 'flex items-center justify-between mb-1.5',
  recentItemsTitle: 'text-[11px] font-mono-num text-slate-600 uppercase font-bold tracking-wide',
  recentItemsStatus: 'text-[10px] font-mono-num text-blue-700 font-bold',
  recentItemsList: 'flex flex-col gap-1.5 max-h-56 overflow-y-auto',
  recentItemCard: 'flex items-center justify-between p-2 rounded bg-slate-50 border border-slate-200 text-xs',
  recentItemInfo: 'min-w-0 pr-2',
  recentItemName: 'font-semibold text-slate-900 truncate',
  recentItemDetails: 'text-[11px] font-mono-num text-slate-500',
  recentItemPrice: 'font-mono-num font-bold text-slate-900 shrink-0',
  emptyCartState: 'text-center py-6 text-slate-400 text-xs',
  saleActions: 'flex flex-col gap-2 pt-2 border-t border-slate-100',
  finishSaleBtn: 'w-full h-11 rounded-lg bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white font-mono-num text-xs font-bold flex items-center justify-center gap-1.5 transition-colors shadow-xs',
  finishSaleIcon: 'material-symbols-outlined text-base',
  returnBtn: 'w-full h-10 rounded-lg bg-white border border-slate-200 hover:bg-slate-100 text-slate-700 font-mono-num text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors shadow-xs',
  returnIcon: 'material-symbols-outlined text-sm text-slate-500',
  scaleWidget: 'bg-white border border-slate-200 p-3 rounded-lg flex flex-col gap-1.5 shadow-xs cursor-pointer hover:border-blue-300 transition-colors',
  scaleWidgetHeader: 'flex items-center justify-between text-slate-600 font-mono-num text-xs',
  scaleWidgetTitleWrapper: 'flex items-center gap-1 font-semibold text-slate-800',
  scaleWidgetIcon: 'material-symbols-outlined text-emerald-600 text-base font-bold',
  scaleWidgetStatus: 'text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200 font-bold text-[10px]',
  scaleWidgetDisplay: 'flex items-baseline justify-between bg-[#f8fafc] border border-slate-200 px-3 py-2 rounded',
  scaleWidgetLabel: 'font-mono-num text-xs text-slate-500 font-bold',
  scaleWidgetValue: 'text-xl font-extrabold text-emerald-700 font-mono-num',
  scaleWidgetUnit: 'text-sm font-bold text-slate-600'
};
