export const styles = {
  container: 'flex flex-col w-full flex-1',
  contentWrapper: 'w-full px-4 lg:px-6 py-5 flex flex-col gap-5',

  /* Top Search Strip */
  topStrip: 'grid grid-cols-1 xl:grid-cols-12 gap-4 items-stretch',
  searchBox: 'xl:col-span-8 bg-white border border-slate-200/60 p-4 rounded-xl flex flex-col justify-center',
  searchHeader: 'flex flex-wrap items-center justify-between mb-2 px-1 gap-2',
  searchHeaderLeft: 'flex items-center gap-2',
  searchTitle: 'text-xs text-slate-400 uppercase tracking-wider font-medium',
  searchStatusDot: 'w-1.5 h-1.5 rounded-full bg-emerald-400',
  searchStatusText: 'text-xs text-slate-400',
  searchShortcuts: 'flex flex-wrap items-center gap-2 text-slate-300 text-xs',
  searchInputWrapper: 'relative flex items-center',
  searchIconWrapper: 'absolute left-3.5 flex items-center pointer-events-none text-slate-300',
  searchIcon: 'material-symbols-outlined text-xl',
  searchInput: 'w-full bg-slate-50 border border-slate-200/60 text-slate-800 text-sm pl-11 pr-24 py-3 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-200 focus:border-blue-400 focus:bg-white placeholder:text-slate-300 transition-all',
  searchBadgesWrapper: 'absolute right-3 flex items-center gap-1.5',
  searchBadgeF2: 'px-2 py-0.5 rounded-md bg-slate-100 text-slate-400 text-xs hidden sm:block',
  searchBadgeFocus: 'px-2 py-0.5 rounded-md bg-slate-100 text-slate-400 text-[11px] hidden sm:block',

  /* Metrics Cards */
  metricsStrip: 'xl:col-span-4 grid grid-cols-1 sm:grid-cols-3 gap-3',
  metricCard: 'bg-white border border-slate-200/60 p-3 rounded-xl flex flex-col justify-between',
  metricTitle: 'text-[11px] text-slate-400 uppercase font-medium',
  metricValueWrapper: 'flex items-baseline gap-1 my-1',
  metricValue: 'text-xl font-bold text-slate-800 font-mono-num',
  metricUnit: 'text-xs text-slate-400',
  metricStatusWrapper: 'text-[11px] font-medium flex items-center gap-1',
  metricStatusIcon: 'material-symbols-outlined text-xs',

  /* Category Filter */
  categoryFilterBar: 'flex items-center gap-2 overflow-x-auto pb-1',
  categoryButtonBase: 'px-3.5 py-2 rounded-xl text-xs font-medium flex items-center gap-2 transition-all shrink-0',
  categoryButtonActive: 'bg-slate-900 text-white',
  categoryButtonInactive: 'bg-white border border-slate-200/60 hover:bg-slate-50 text-slate-500',
  categoryIcon: 'material-symbols-outlined text-base',
  categoryShortcutBase: 'px-1.5 py-0.5 rounded-md text-[10px] hidden sm:block',
  categoryShortcutActive: 'bg-white/15 text-white/80',
  categoryShortcutInactive: 'bg-slate-100 text-slate-400',

  /* Products Grid */
  mainLayout: 'grid grid-cols-1 lg:grid-cols-12 gap-5 items-start',
  productsGrid: 'lg:col-span-9 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4',
  productCard: 'group relative bg-white border border-slate-200/60 hover:border-slate-300 p-3.5 rounded-xl transition-all flex flex-col justify-between cursor-pointer',
  productImageWrapper: 'relative w-full h-32 rounded-lg bg-slate-50 overflow-hidden mb-3',
  productImage: 'w-full h-full object-cover group-hover:scale-105 transition-transform duration-300',
  productCodeBadge: 'absolute top-2 left-2 px-2 py-0.5 rounded-md bg-white/90 backdrop-blur-sm text-slate-500 font-mono-num text-[11px]',
  productCategoryBadgeBase: 'absolute bottom-2 right-2 px-2 py-0.5 rounded-md text-[11px] font-medium',
  productCategoryBadgeAmber: 'bg-amber-50 text-amber-600',
  productCategoryBadgeBlue: 'bg-blue-50 text-blue-500',
  productInfoWrapper: 'mb-2',
  productTitle: 'text-sm font-semibold text-slate-700 group-hover:text-slate-900 line-clamp-1 transition-colors',
  productBrand: 'text-xs text-slate-400',
  productActionWrapper: 'pt-2 border-t border-slate-100',
  productPriceRow: 'flex flex-wrap items-baseline justify-between mb-2.5 gap-2',
  productPriceCol: 'flex flex-col',
  productPriceLabel: 'text-[10px] text-slate-400 uppercase',
  productPriceValueWrapper: 'flex items-baseline gap-0.5',
  productPriceCurrency: 'text-xs text-slate-500 font-mono-num',
  productPriceValue: 'text-xl font-bold text-slate-800 font-mono-num',
  productStockCol: 'text-left sm:text-right flex flex-col items-start sm:items-end',
  productStockLabel: 'text-[10px] text-slate-400 uppercase',
  productStockValueBase: 'text-sm font-semibold font-mono-num',
  productActionButton: 'w-full h-9 rounded-lg bg-slate-50 hover:bg-slate-900 text-slate-500 hover:text-white border border-slate-200/60 hover:border-slate-900 text-xs font-medium flex items-center justify-center gap-1.5 transition-all group-hover:bg-slate-900 group-hover:text-white group-hover:border-slate-900',
  productActionIcon: 'material-symbols-outlined text-base',
  productActionShortcut: 'px-1.5 py-0.5 rounded bg-white/10 text-[10px] hidden sm:block',
  emptyState: 'col-span-full py-16 text-center text-slate-300 bg-white border border-slate-200/60 rounded-xl',
  emptyStateIcon: 'material-symbols-outlined text-4xl block mb-3 text-slate-200',

  /* Sidebar */
  sidebarLayout: 'lg:col-span-3 flex flex-col gap-4 sticky top-20',
  activeSaleCard: 'bg-white border border-slate-200/60 p-4 rounded-xl flex flex-col gap-3',
  activeSaleHeader: 'flex flex-wrap items-center justify-between gap-2',
  activeSaleTitleWrapper: 'flex items-center gap-1.5',
  activeSaleIcon: 'material-symbols-outlined text-slate-400 text-lg',
  activeSaleTitle: 'text-xs text-slate-500 font-medium uppercase tracking-wider',
  activeSaleStatus: 'px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-500 text-[10px] font-medium',

  /* Total Display */
  totalDisplay: 'bg-slate-50 p-4 rounded-xl flex flex-col justify-center',
  totalDisplayLabel: 'text-[10px] text-slate-400 uppercase tracking-wider',
  totalDisplayValueWrapper: 'flex items-baseline gap-1 my-1',
  totalDisplayCurrency: 'text-xl font-semibold text-slate-400 font-mono-num',
  totalDisplayValue: 'text-4xl font-bold text-slate-900 font-mono-num tracking-tight',
  totalDisplayFooter: 'flex flex-wrap items-center justify-between text-xs text-slate-400 font-mono-num gap-2',

  /* Recent Items */
  recentItemsHeader: 'flex flex-wrap items-center justify-between mb-2 gap-2',
  recentItemsTitle: 'text-[11px] text-slate-400 uppercase tracking-wider font-medium',
  recentItemsStatus: 'text-[10px] text-slate-500 font-mono-num font-medium',
  recentItemsList: 'flex flex-col gap-1.5 max-h-56 overflow-y-auto',
  recentItemCard: 'flex items-center justify-between p-2.5 rounded-lg bg-slate-50 text-xs',
  recentItemInfo: 'min-w-0 pr-2',
  recentItemName: 'font-medium text-slate-600 truncate',
  recentItemDetails: 'text-[11px] text-slate-400 font-mono-num',
  recentItemPrice: 'font-mono-num font-semibold text-slate-700 shrink-0',
  emptyCartState: 'text-center py-8 text-slate-300 text-xs',

  /* Sale Actions */
  saleActions: 'flex flex-col gap-2 pt-3 border-t border-slate-100',
  finishSaleBtn: 'w-full h-11 rounded-xl bg-slate-900 hover:bg-slate-800 disabled:opacity-40 text-white text-sm font-semibold flex items-center justify-center gap-1.5 transition-colors',
  finishSaleIcon: 'material-symbols-outlined text-base',
  returnBtn: 'w-full h-10 rounded-xl bg-white border border-slate-200/60 hover:bg-slate-50 text-slate-500 text-xs font-medium flex items-center justify-center gap-1.5 transition-colors',
  returnIcon: 'material-symbols-outlined text-sm text-slate-400',

  /* Scale Widget */
  scaleWidget: 'bg-white border border-slate-200/60 p-3 rounded-xl flex flex-col gap-1.5 cursor-pointer hover:border-slate-300 transition-colors',
  scaleWidgetHeader: 'flex flex-wrap items-center justify-between text-xs gap-2',
  scaleWidgetTitleWrapper: 'flex items-center gap-1 text-slate-500',
  scaleWidgetIcon: 'material-symbols-outlined text-slate-400 text-base',
  scaleWidgetStatus: 'text-emerald-500 bg-emerald-50 px-2 py-0.5 rounded-full text-[10px] font-medium',
  scaleWidgetDisplay: 'flex items-baseline justify-between bg-slate-50 px-3 py-2.5 rounded-lg',
  scaleWidgetLabel: 'text-xs text-slate-400',
  scaleWidgetValue: 'text-xl font-bold text-slate-800 font-mono-num',
  scaleWidgetUnit: 'text-sm text-slate-500'
};
