export const styles = {
  container: "flex flex-col w-full flex-1",
  wrapper: "w-full px-4 lg:px-6 py-4 flex flex-col gap-4",
  grid: "grid grid-cols-1 lg:grid-cols-12 gap-4 items-start",
  leftColumn: "lg:col-span-8 flex flex-col gap-4",
  
  barcodeForm: "bg-white border border-slate-200 p-2.5 rounded-lg shadow-xs flex flex-wrap sm:flex-nowrap items-center gap-3",
  barcodeIconWrapper: "text-blue-700 pl-2 flex items-center hidden sm:flex",
  barcodeIcon: "material-symbols-outlined text-2xl font-bold",
  barcodeInput: "w-full sm:flex-1 bg-transparent border-none text-slate-900 placeholder:text-slate-400 font-medium text-base focus:outline-none focus:ring-0",
  barcodeActions: "flex flex-wrap items-center gap-1.5 w-full sm:w-auto",
  btnSearch: "px-2.5 py-1 rounded bg-blue-50 text-[#004ac6] border border-blue-200 text-xs font-mono-num font-bold hover:bg-blue-100 transition-colors",
  btnEnter: "px-3 py-1 rounded bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-200 text-xs font-mono-num font-bold transition-colors",
  qtyControl: "flex items-center border border-slate-200 rounded sm:ml-2 bg-slate-50 mt-2 sm:mt-0",
  qtyLabel: "px-2 text-xs font-mono-num font-bold text-slate-500",
  qtyBtnMinus: "w-7 h-7 flex items-center justify-center hover:bg-slate-200 text-slate-700 font-bold border-l border-slate-200",
  qtyValue: "w-8 text-center text-xs font-mono-num font-bold text-slate-900",
  qtyBtnPlus: "w-7 h-7 flex items-center justify-center hover:bg-slate-200 text-slate-700 font-bold border-l border-slate-200",
  
  lastScannedContainer: "bg-white border border-slate-200 p-3.5 rounded-lg shadow-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 transition-all",
  lastScannedLeft: "flex items-center gap-3.5 w-full sm:w-auto",
  lastScannedImgWrapper: "w-14 h-14 rounded bg-slate-100 border border-slate-200 overflow-hidden shrink-0",
  lastScannedImg: "w-full h-full object-cover",
  lastScannedInfo: "flex flex-col min-w-0",
  lastScannedTagWrapper: "flex items-center gap-2",
  lastScannedTag: "px-2 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 text-[10px] font-mono-num font-bold",
  lastScannedCode: "text-xs font-mono-num text-slate-500",
  lastScannedName: "text-base font-bold text-slate-900 mt-0.5 leading-snug line-clamp-1",
  lastScannedRight: "flex flex-row sm:flex-col items-center sm:items-end justify-between w-full sm:w-auto shrink-0 pl-0 sm:pl-4 border-t sm:border-t-0 sm:border-l border-slate-100 pt-3 sm:pt-0",
  lastScannedDetails: "text-xs font-mono-num text-slate-500",
  lastScannedSubtotal: "text-2xl font-bold text-[#004ac6] font-mono-num tracking-tight",
  
  emptyScannedContainer: "bg-white border border-dashed border-slate-300 p-4 rounded-lg flex flex-col sm:flex-row items-center justify-center text-slate-400 gap-2 text-center sm:text-left",
  emptyScannedIcon: "material-symbols-outlined text-xl mb-1 sm:mb-0",
  emptyScannedText: "text-sm font-medium",

  tableContainer: "bg-white border border-slate-200 rounded-lg shadow-xs overflow-hidden flex flex-col",
  tableWrapper: "overflow-x-auto min-h-[380px] max-h-[500px] overflow-y-auto w-full",
  table: "w-full text-left text-sm whitespace-nowrap sm:whitespace-normal",
  thead: "sticky top-0 bg-[#f8fafc] border-b border-slate-200 z-10",
  trHead: "text-xs font-mono-num text-slate-500 uppercase tracking-wider",
  thHash: "py-2.5 px-3 w-10 text-center",
  thCode: "py-2.5 px-3 w-36",
  thDesc: "py-2.5 px-3",
  thQty: "py-2.5 px-3 w-28 text-center",
  thPrice: "py-2.5 px-3 w-28 text-right",
  thSubtotal: "py-2.5 px-3 w-28 text-right",
  thAction: "py-2.5 px-3 w-16 text-center",
  tbody: "divide-y divide-slate-100 font-mono-num",
  
  trBodyBase: "transition-colors hover:bg-slate-50/80",
  trBodyLast: "bg-blue-50/40 text-slate-900 font-medium",
  trBodyNormal: "text-slate-800",
  tdHash: "py-2.5 px-3 text-center text-xs text-slate-500",
  tdCode: "py-2.5 px-3 text-xs text-slate-600",
  tdDesc: "py-2.5 px-3 font-sans",
  tdDescWrapper: "flex items-center gap-2",
  tdDescName: "font-semibold text-slate-900",
  tdDescIcon: "material-symbols-outlined text-emerald-600 text-xs font-bold",
  tdQty: "py-2.5 px-3 text-center",
  tdQtyWrapper: "inline-flex items-center gap-1.5",
  tdQtyBtn: "w-5 h-5 rounded bg-slate-100 hover:bg-slate-200 text-slate-600 flex items-center justify-center text-xs font-bold",
  tdQtyTextBase: "px-1.5 text-xs font-bold",
  tdQtyTextLast: "text-[#004ac6]",
  tdQtyTextNormal: "text-slate-900",
  tdPrice: "py-2.5 px-3 text-right text-xs text-slate-700",
  tdSubtotalBase: "py-2.5 px-3 text-right font-bold text-sm",
  tdSubtotalLast: "text-[#004ac6]",
  tdSubtotalNormal: "text-slate-900",
  tdAction: "py-2.5 px-3 text-center",
  tdActionBtn: "text-slate-400 hover:text-red-600 transition-colors p-1",
  tdActionIcon: "material-symbols-outlined text-base",

  tdEmpty: "py-12 text-center text-slate-400 font-sans whitespace-normal",
  tdEmptyIcon: "material-symbols-outlined text-4xl block mb-2 text-slate-300",

  tableBottom: "p-3 bg-[#f8fafc] border-t border-slate-200 flex flex-wrap items-center justify-between text-xs text-slate-600 font-mono-num gap-2",
  tableBottomLeft: "flex flex-wrap items-center gap-2 sm:gap-4",
  tableBottomStat: "flex items-center gap-1.5",
  tableBottomIcon: "material-symbols-outlined text-slate-500 text-sm",
  tableBottomStrong: "text-slate-900 font-bold",
  tableBottomRight: "flex items-center gap-1 text-emerald-700 font-medium",
  tableBottomRightIcon: "material-symbols-outlined text-emerald-600 text-sm",

  rightColumn: "lg:col-span-4 flex flex-col gap-4",
  customerHeader: "bg-white border border-slate-200 p-3 rounded-lg shadow-xs flex items-center justify-between",
  customerHeaderLeft: "flex items-center gap-2 min-w-0",
  customerHeaderIcon: "material-symbols-outlined text-slate-400 text-lg",
  customerHeaderText: "text-xs font-semibold text-slate-800 truncate",
  customerHeaderBtn: "text-blue-600 hover:text-blue-800 transition-colors p-1",
  customerHeaderBtnIcon: "material-symbols-outlined text-sm font-bold",

  totalsCard: "bg-white border border-slate-200 p-4 rounded-lg shadow-xs flex flex-col gap-3",
  totalsRow: "flex items-center justify-between text-sm text-slate-600 font-mono-num",
  totalsLabel: "uppercase text-xs font-semibold",
  totalsValueGross: "font-bold text-slate-900 text-base",
  totalsRowDiscountLeft: "flex items-center gap-1.5",
  totalsPromoTag: "px-1.5 py-0.2 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 text-[10px] font-bold",
  totalsValueDiscount: "font-bold text-emerald-700",
  totalsValueAddition: "font-bold text-slate-900",

  hugeTotalCard: "bg-[#f0fdf4] border-2 border-[#bbf7d0] rounded-xl p-4 mt-1 flex flex-col items-center justify-center text-center",
  hugeTotalLabel: "text-[11px] font-mono-num font-bold text-emerald-800 uppercase tracking-widest",
  hugeTotalValueWrapper: "text-4xl font-extrabold text-[#006e2d] font-mono-num tracking-tight mt-0.5",
  hugeTotalCurrency: "text-2xl font-bold mr-1",
  hugeTotalStatus: "flex items-center gap-1.5 text-[11px] font-mono-num text-emerald-700 font-medium mt-1",
  hugeTotalPulse: "w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse",

  quickPaymentSection: "pt-2",
  quickPaymentTitle: "text-[10px] font-mono-num uppercase tracking-wider text-slate-500 font-bold block mb-2",
  quickPaymentGrid: "grid grid-cols-2 gap-2",
  quickPaymentBtn: "p-2.5 rounded-lg bg-slate-50 hover:bg-slate-100 border border-slate-200 flex flex-col items-center justify-center text-slate-800 transition-all group",
  quickPaymentIconCash: "material-symbols-outlined text-emerald-600 text-xl group-hover:scale-110 transition-transform",
  quickPaymentIconPix: "material-symbols-outlined text-emerald-600 text-xl group-hover:scale-110 transition-transform",
  quickPaymentIconDebit: "material-symbols-outlined text-blue-600 text-xl group-hover:scale-110 transition-transform",
  quickPaymentIconCredit: "material-symbols-outlined text-amber-600 text-xl group-hover:scale-110 transition-transform",
  quickPaymentBtnLabel: "text-xs font-bold text-slate-900 mt-1",
  quickPaymentBtnKey: "text-[10px] font-mono-num text-slate-500 hidden sm:inline",

  mainActionsSection: "flex flex-col gap-2 pt-2 border-t border-slate-100",
  btnFinish: "w-full h-12 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-sm shadow-sm transition-all flex items-center justify-between px-4",
  btnFinishLeft: "flex items-center gap-2",
  btnFinishIcon: "material-symbols-outlined text-lg",
  btnFinishKey: "px-2 py-0.5 rounded bg-emerald-700 text-white font-mono-num text-xs font-bold hidden sm:inline-block",

  secondaryActionsGrid: "grid grid-cols-2 gap-2",
  btnPark: "h-10 rounded-lg bg-white border border-slate-200 hover:bg-slate-100 disabled:opacity-50 text-slate-700 text-xs font-mono-num font-semibold flex flex-col sm:flex-row items-center justify-center gap-1 transition-colors text-center p-1",
  btnParkIcon: "material-symbols-outlined text-sm hidden sm:block",
  btnCancel: "h-10 rounded-lg bg-white border border-slate-200 hover:bg-red-50 hover:text-red-700 hover:border-red-200 disabled:opacity-50 text-slate-700 text-xs font-mono-num font-semibold flex flex-col sm:flex-row items-center justify-center gap-1 transition-colors text-center p-1",
  btnCancelIcon: "material-symbols-outlined text-sm hidden sm:block",
};
