export const styles = {
  container: "flex flex-col w-full flex-1",
  wrapper: "w-full px-4 lg:px-6 py-5 flex flex-col gap-5 flex-1",
  grid: "grid grid-cols-1 lg:grid-cols-12 gap-5 items-stretch flex-1",
  leftColumn: "lg:col-span-8 flex flex-col gap-4",

  /* Barcode Input — clean single-line */
  barcodeForm: "bg-white border border-slate-200/60 p-3 rounded-xl flex flex-wrap sm:flex-nowrap items-center gap-3",
  barcodeIconWrapper: "text-slate-400 pl-1 hidden sm:flex items-center",
  barcodeIcon: "material-symbols-outlined text-xl",
  barcodeInput: "w-full sm:flex-1 bg-transparent border-none text-slate-800 placeholder:text-slate-300 font-medium text-sm focus:outline-none",
  barcodeActions: "flex flex-wrap items-center gap-1.5 w-full sm:w-auto",
  btnSearch: "px-3 py-1.5 rounded-lg bg-slate-100 text-slate-600 text-xs font-medium hover:bg-slate-200 transition-colors",
  btnEnter: "px-3 py-1.5 rounded-lg bg-slate-900 text-white text-xs font-medium hover:bg-slate-800 transition-colors",
  qtyControl: "flex items-center border border-slate-200/60 rounded-lg sm:ml-2 bg-white mt-2 sm:mt-0",
  qtyLabel: "px-2.5 text-xs text-slate-400 font-medium",
  qtyBtnMinus: "w-7 h-7 flex items-center justify-center hover:bg-slate-100 text-slate-500 rounded-l-lg transition-colors",
  qtyValue: "w-8 text-center text-sm font-semibold text-slate-800",
  qtyBtnPlus: "w-7 h-7 flex items-center justify-center hover:bg-slate-100 text-slate-500 rounded-r-lg transition-colors",

  /* Last Scanned Item — subtle highlight */
  lastScannedContainer: "bg-white border border-slate-200/60 p-4 rounded-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4",
  lastScannedLeft: "flex items-center gap-3 w-full sm:w-auto",
  lastScannedImgWrapper: "w-12 h-12 rounded-lg bg-slate-50 overflow-hidden shrink-0",
  lastScannedImg: "w-full h-full object-cover",
  lastScannedInfo: "flex flex-col min-w-0",
  lastScannedTagWrapper: "flex items-center gap-2",
  lastScannedTag: "px-1.5 py-0.5 rounded-md bg-blue-50 text-blue-600 text-[10px] font-medium",
  lastScannedCode: "text-xs text-slate-400 font-mono-num",
  lastScannedName: "text-sm font-semibold text-slate-800 mt-0.5 leading-snug line-clamp-1",
  lastScannedRight: "flex flex-row sm:flex-col items-center sm:items-end justify-between w-full sm:w-auto shrink-0",
  lastScannedDetails: "text-xs text-slate-400 font-mono-num",
  lastScannedSubtotal: "text-xl font-bold text-slate-900 font-mono-num",

  emptyScannedContainer: "border border-dashed border-slate-200 p-5 rounded-xl flex flex-col sm:flex-row items-center justify-center text-slate-300 gap-2 text-center sm:text-left",
  emptyScannedIcon: "material-symbols-outlined text-2xl",
  emptyScannedText: "text-sm",

  /* Items Table — clean and airy */
  tableContainer: "bg-white border border-slate-200/60 rounded-xl overflow-hidden flex flex-col flex-1",
  tableWrapper: "overflow-x-auto flex-1 overflow-y-auto w-full",
  table: "w-full text-left text-sm whitespace-nowrap sm:whitespace-normal",
  thead: "sticky top-0 bg-slate-50/80 backdrop-blur-sm border-b border-slate-100 z-10",
  trHead: "text-[11px] text-slate-400 uppercase tracking-wider font-medium",
  thHash: "py-3 px-3 w-10 text-center",
  thCode: "py-3 px-3 w-36",
  thDesc: "py-3 px-3",
  thQty: "py-3 px-3 w-28 text-center",
  thPrice: "py-3 px-3 w-28 text-right",
  thSubtotal: "py-3 px-3 w-28 text-right",
  thAction: "py-3 px-3 w-16 text-center",
  tbody: "divide-y divide-slate-50",

  trBodyBase: "transition-colors hover:bg-slate-50/50",
  trBodyLast: "bg-blue-50/30",
  trBodyNormal: "",
  tdHash: "py-3 px-3 text-center text-xs text-slate-300 font-mono-num",
  tdCode: "py-3 px-3 text-xs text-slate-400 font-mono-num",
  tdDesc: "py-3 px-3",
  tdDescWrapper: "flex items-center gap-2",
  tdDescName: "font-medium text-slate-700 text-sm",
  tdDescIcon: "material-symbols-outlined text-blue-400 text-xs",
  tdQty: "py-3 px-3 text-center",
  tdQtyWrapper: "inline-flex items-center gap-1.5",
  tdQtyBtn: "w-6 h-6 rounded-md bg-slate-50 hover:bg-slate-100 text-slate-400 flex items-center justify-center text-xs transition-colors",
  tdQtyTextBase: "px-1.5 text-sm font-medium font-mono-num",
  tdQtyTextLast: "text-slate-900",
  tdQtyTextNormal: "text-slate-600",
  tdPrice: "py-3 px-3 text-right text-sm text-slate-400 font-mono-num",
  tdSubtotalBase: "py-3 px-3 text-right font-semibold text-sm font-mono-num",
  tdSubtotalLast: "text-slate-900",
  tdSubtotalNormal: "text-slate-700",
  tdAction: "py-3 px-3 text-center",
  tdActionBtn: "text-slate-300 hover:text-red-500 transition-colors p-1",
  tdActionIcon: "material-symbols-outlined text-base",

  tdEmpty: "py-16 text-center text-slate-300 whitespace-normal",
  tdEmptyIcon: "material-symbols-outlined text-4xl block mb-3 text-slate-200",

  tableBottom: "px-4 py-3 bg-slate-50/50 border-t border-slate-100 flex flex-wrap items-center justify-between text-xs text-slate-400 gap-2",
  tableBottomLeft: "flex flex-wrap items-center gap-3",
  tableBottomStat: "flex items-center gap-1",
  tableBottomIcon: "material-symbols-outlined text-slate-300 text-sm",
  tableBottomStrong: "text-slate-600 font-medium",
  tableBottomRight: "flex items-center gap-1 text-slate-400",
  tableBottomRightIcon: "material-symbols-outlined text-slate-300 text-sm",

  /* Right Column — Totals & Actions */
  rightColumn: "lg:col-span-4 flex flex-col gap-4",
  customerHeader: "bg-white border border-slate-200/60 p-3 rounded-xl flex items-center justify-between",
  customerHeaderLeft: "flex items-center gap-2 min-w-0",
  customerHeaderIcon: "material-symbols-outlined text-slate-300 text-lg",
  customerHeaderText: "text-sm text-slate-500 truncate",
  customerHeaderBtn: "text-slate-400 hover:text-slate-600 transition-colors p-1",
  customerHeaderBtnIcon: "material-symbols-outlined text-sm",

  totalsCard: "bg-white border border-slate-200/60 p-5 rounded-xl flex flex-col gap-3 flex-1",
  totalsRow: "flex items-center justify-between text-sm",
  totalsLabel: "text-slate-400 text-xs font-medium",
  totalsValueGross: "font-semibold text-slate-700 font-mono-num",
  totalsRowDiscountLeft: "flex items-center gap-1.5",
  totalsPromoTag: "px-1.5 py-0.5 rounded-md bg-emerald-50 text-emerald-500 text-[10px] font-medium",
  totalsValueDiscount: "font-medium text-emerald-600 font-mono-num",
  totalsValueAddition: "font-medium text-slate-600 font-mono-num",

  /* Hero Total — the star of the screen */
  hugeTotalCard: "bg-slate-50 rounded-xl p-6 mt-2 flex flex-col items-center justify-center text-center",
  hugeTotalLabel: "text-[11px] text-slate-400 uppercase tracking-widest font-medium",
  hugeTotalValueWrapper: "text-4xl font-bold text-slate-900 font-mono-num tracking-tight mt-1",
  hugeTotalCurrency: "text-2xl font-semibold mr-1 text-slate-400",
  hugeTotalStatus: "flex items-center gap-1.5 text-[11px] text-slate-400 mt-2",
  hugeTotalPulse: "w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse",

  /* Quick Payment Buttons */
  quickPaymentSection: "pt-3",
  quickPaymentTitle: "text-[10px] uppercase tracking-wider text-slate-300 font-medium block mb-2",
  quickPaymentGrid: "grid grid-cols-2 gap-2",
  quickPaymentBtn: "p-3 rounded-xl bg-slate-50 hover:bg-slate-100 border border-transparent hover:border-slate-200/60 flex flex-col items-center justify-center text-slate-500 transition-all group",
  quickPaymentIconCash: "material-symbols-outlined text-slate-400 text-xl group-hover:text-emerald-500 transition-colors",
  quickPaymentIconPix: "material-symbols-outlined text-slate-400 text-xl group-hover:text-emerald-500 transition-colors",
  quickPaymentIconDebit: "material-symbols-outlined text-slate-400 text-xl group-hover:text-blue-500 transition-colors",
  quickPaymentIconCredit: "material-symbols-outlined text-slate-400 text-xl group-hover:text-amber-500 transition-colors",
  quickPaymentBtnLabel: "text-xs font-medium text-slate-600 mt-1",
  quickPaymentBtnKey: "text-[10px] text-slate-300 hidden sm:inline",

  /* Main CTA */
  mainActionsSection: "flex flex-col gap-2 pt-3 border-t border-slate-100 mt-auto",
  btnFinish: "w-full h-12 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-semibold text-sm transition-all flex items-center justify-between px-5",
  btnFinishLeft: "flex items-center gap-2",
  btnFinishIcon: "material-symbols-outlined text-lg",
  btnFinishKey: "px-2 py-0.5 rounded-md bg-white/10 text-white/70 font-mono-num text-xs hidden sm:inline-block",

  secondaryActionsGrid: "grid grid-cols-2 gap-2",
  btnPark: "h-10 rounded-xl bg-white border border-slate-200/60 hover:bg-slate-50 disabled:opacity-40 text-slate-500 text-xs font-medium flex flex-col sm:flex-row items-center justify-center gap-1 transition-colors text-center p-1",
  btnParkIcon: "material-symbols-outlined text-sm hidden sm:block",
  btnCancel: "h-10 rounded-xl bg-white border border-slate-200/60 hover:bg-red-50 hover:text-red-500 hover:border-red-100 disabled:opacity-40 text-slate-500 text-xs font-medium flex flex-col sm:flex-row items-center justify-center gap-1 transition-colors text-center p-1",
  btnCancelIcon: "material-symbols-outlined text-sm hidden sm:block",
};
